# Generated by Django 5.1.1 on 2024-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('driver', 'Driver'), ('rider', 'Rider')], default='driver', max_length=225)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('expo_tokens', models.CharField(max_length=225)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
